#!/usr/bin/env sh
ROOT_DIR=$(git rev-parse --show-toplevel)
GIT_DIRECTORY=$1

# If this environment variable if specified we will return all the files so the
# checks run on all the files not only changed ones.
if [ "${FORCE_CHECK_ALL_FILES}" = "true" ]; then
    echo $(find ${ROOT_DIR}/packs/* -maxdepth 0 -type d)
    exit 0
fi

cd $GIT_DIRECTORY
echo $(git diff --name-only master -- 'packs/*' | xargs -I FILENAME dirname FILENAME | awk -F'/' '/^\./ {next} /^[^\/]+$/ {next} /^scripts/ {next} /.*/{print $1"/"$2"/"}' | uniq) 
