#!/usr/bin/env sh
GIT_DIRECTORY=$1

cd $GIT_DIRECTORY
echo $(git diff --name-only master -- 'packs/*' | xargs -I FILENAME dirname FILENAME | awk -F'/' '/^\./ {next} /^[^\/]+$/ {next} /^scripts/ {next} /.*/{print $1"/"$2"/"}' | uniq) 
