#!/usr/bin/env sh
GIT_DIRECTORY=$1
BASE_BRANCH="origin/master"

cd $GIT_DIRECTORY
echo $(git diff --name-only ${BASE_BRANCH} | xargs -I FILENAME dirname FILENAME | awk '/^\./ {next} /.*/{print "./"$1}')
