#!/usr/bin/env sh
ROOT_DIRECTORY=$1
BASE_BRANCH="origin/master"

cd ${ROOT_DIRECTORY}
# Note: We include all but deleted files ("D" flag)
echo $(git diff --diff-filter=ACMRTUXB --name-only ${BASE_BRANCH} | xargs -I FILENAME dirname FILENAME | awk '/^\./ {next} /.*/{print "./"$1}')
