#!/usr/bin/env sh
ROOT_DIR=$(git rev-parse --show-toplevel)
GIT_DIRECTORY=$1
BASE_BRANCH="origin/master"

# If this environment variable if specified we will return all the files so the
# checks run on all the files not only changed ones.
if [ "${FORCE_CHECK_ALL_FILES}" = "true" ]; then
    echo $(find ${ROOT_DIR}/packs/* -name "*.py")
    exit 0
fi

cd $GIT_DIRECTORY
echo $(git diff --name-only ${BASE_BRANCH} -- '*.py')
