#!/usr/bin/env sh
ROOT_DIRECTORY=$1
BASE_BRANCH="origin/master"

# If this environment variable if specified we will return all the files so the
# checks run on all the files not only changed ones.
if [ "${FORCE_CHECK_ALL_FILES}" = "true" ]; then
    echo $(find ${ROOT_DIRECTORY}/packs/* -name "*.py")
    exit 0
fi

if [ ! -z "${FORCE_CHECK_PACK}" ] && [ "${FORCE_CHECK_PACK}" != "false" ]; then
    echo $(find ${ROOT_DIRECTORY}/packs/${FORCE_CHECK_PACK} -name "*.py")
    exit 0
fi

cd ${ROOT_DIRECTORY}
# Note: We include all but deleted files ("D" flag)
echo $(git diff --diff-filter=ACMRTUXB --name-only ${BASE_BRANCH} -- '*.py')
