# notify_hubot.yaml
---
name: "notify_hubot"
pack: "hubot"
enabled: true
description: "Notification rule to send messages to Hubot"
trigger:
  pack: "hubot"
  type: "core.st2.generic.notifytrigger"
criteria:
  trigger.route:
    pattern: "hubot"
    type: "equals"
action:
  ref: hubot.post_result
  parameters:
    channel: "{{trigger.data.source_channel}}"
    user: "{{trigger.data.user}}"
    result: "{{trigger}}"
