---
name: check_load_procs
pack: nagios
description: Check running procs on host when load is high
enabled: true
trigger:
  type: nagios.service-state-change
criteria:
  trigger.service:
    pattern: "(.*)_check_loadavg"
    type: matchregex
  trigger.state_type:
    pattern: HARD
    type: matchregex
action:
  ref: check_procs
  parameters:
    hosts: "{{trigger.host}}"
    cmd: state R
