---
name: check_load_procd
pack: nagios
description: Check D state procs on host when load is high
enabled: true
trigger:
  type: nagios.service.state_change
criteria:
  trigger.service:
    pattern: "(.*)_check_loadavg"
    type: matchregex
  trigger.state_type:
    pattern: HARD
    type: matchregex
action:
  ref: check_procs
  parameters:
    hosts: "{{trigger.host}}"
    cmd: state D
